version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: neo4j:2025.07.0
    environment:
      NEO4J_AUTH: conecte_os_globais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7474:7474"
    volumes:
      - neo4j_data:/var/lib/neo4j/data

volumes:
  neo4j_data: